### ISSUE TITLE
default policy should be able to set individually for 'incoming' OR 'outgoing' traffic

### ISSUE THREAD

**Issue by xbeta** [Oefenweb/ansible-ufw#20]
from the official guide:
http://docs.ansible.com/ansible/ufw_module.html

**Comment by tersmitten** [comment]
Have a look at #14. Does that add the feature that you're requesting?

**Comment by xbeta** [comment]
that works

**Comment by tersmitten** [comment]
I'll try to finish it soon.

**Comment by tersmitten** [comment]
Fixed in #23
