### ISSUE TITLE
nf_conntrack_tcp_be_liberal does not exists

### ISSUE THREAD

**Issue by kmonticolo** [Oefenweb/ansible-ufw#32]
/proc/sys/net/netfilter/nf_conntrack_tcp_be_liberal does not exists in Ubuntu 18.04 bionic

**Comment by tersmitten** [comment]
Does it need a different fix?

**Comment by kmonticolo** [comment]
the one from #34 works for me, but for some reason it doesn't pass idempotence test on Python: 2.7 and ANSIBLE_VERSION=2.8.0
