### ISSUE TITLE
Recommended approach for "before.rules"?

### ISSUE THREAD

**Issue by niftylettuce** [Oefenweb/ansible-ufw#38]
How would you recommend this be done in Ansible?  Could this package have support added for this?

```sh
sudo vim /etc/ufw/before.rules
```

```diff
# rules should be added to one of these chains:
#   ufw-before-input
#   ufw-before-output
#   ufw-before-forward
#
+
+*nat
+:PREROUTING ACCEPT [0:0]
+-A PREROUTING -p tcp -m tcp --dport 80 -j REDIRECT --to-port 8080
+-A PREROUTING -p tcp -m tcp --dport 443 -j REDIRECT --to-port 8443
+COMMIT
+
# Don't delete these required lines, otherwise there will be errors
*filter
:ufw-before-input - [0:0]
:ufw-before-output - [0:0]
:ufw-before-forward - [0:0]
:ufw-not-local - [0:0]
# End required lines
```

```sh
sudo systemctl restart ufw
```

**Comment by tersmitten** [comment]
See the proposed solution in #21 (https://github.com/Oefenweb/ansible-ufw/issues/21#issuecomment-613410223). Is this something that could work for you?

**Comment by niftylettuce** [comment]
@tersmitten Awesome!  I left a comment here https://github.com/Oefenweb/ansible-ufw/issues/21#issuecomment-651105135 - looks great.  I will close this in favor of #21.  Also, are you available for hire?  Would love you to review some config and possibly help with tests that I'm working on for https://forwardemail.net new infrastructure.

**Comment by tersmitten** [comment]
>Would love you to review some config and possibly help with tests that I'm working on for https://forwardemail.net new infrastructure.

Feel free to contact me by mail (mischa@mts-webdev.nl)

**Comment by niftylettuce** [comment]
Done
